name: Build Android APK

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
      - name: Kodu Cek
        uses: actions/checkout@v4

      - name: Node.js Kur
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Java JDK Kur
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Paketleri Yukle
        run: npm install

      - name: Eksik Android Projesini Sifirdan Oluştur
        run: |
          rm -rf android
          npx expo prebuild --platform android --clean

      - name: Gradlew Yetkisi Ver
        run: |
          cd android
          chmod +x gradlew

      - name: APK Derle
        run: |
          cd android
          ./gradlew assembleRelease --no-daemon

      - name: APK Dosyasini Hazirla
        uses: actions/upload-artifact@v4
        with:
          name: HeartBeat-Release-APK
          path: android/app/build/outputs/apk/release/app-release.apk
